name: conda_enlighten3

channels:
    - defaults
    - conda-forge

dependencies:
    - numpy
    - pandas
    - pexpect
    - pip
    - psutil
    - python
    - pytest
    - scipy
    - xlwt
    - qimage2ndarray
    - pywin32
